"""
This file is automatically generated by Flask-Batteries. 

Do not remove the --flask_batteries_mark XXXXXX-- lines. 
These lines are used by Flask-Batteries when installing extensions.
"""

import os


class Config:
    SECRET_KEY = os.environ.get("SECRET_KEY", os.urandom(24))
    DEBUG = False
    TESTING = False
    USE_WEBPACK_DEV_SERVER = False
    # --flask_batteries_mark base_config--


class ProductionConfig(Config):
    pass
    # --flask_batteries_mark production_config--


class DevelopmentConfig(Config):
    DEBUG = True
    ENV = "development"
    # --flask_batteries_mark development_config--


class TestingConfig(Config):
    TESTING = True
    ENV = "testing"
    # --flask_batteries_mark testing_config--
